# Generated by Django 3.2.20 on 2023-09-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230905_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('group_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user_6986', error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.group')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
    ]
