# Generated by Django 3.2.20 on 2023-09-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
    ]
