# Generated by Django 3.2.20 on 2023-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_question_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='새로운 그룹', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='새로운 닉네임1694086780.7053921', error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True),
        ),
    ]
