# Generated by Django 3.2.20 on 2023-09-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230907_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='새로운 닉네임1694157058.1091416', error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('group', 'number')},
        ),
    ]
